# archivo: _config.yml 
title: "Semimetales de Weyl"
author: Antonio Doñez
logo:  images/FQ-bw.png
#
launch_buttons:
  colab_url      : https://colab.research.google.com # The URL of Google Colab (e.g., https://colab.research.google.com)
  binderhub_url  : https://mybinder.org
  thebe          : true

notebook_interface : "notebook"




latex:
  latex_engine : "xelatex"      
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

execute:
  execute_notebooks: cache


parse:
  myst_enable_extensions:
                                 # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
    - linkify
    - substitution
    - colon_fence  
